travis:
  secure:
    BINSTAR_TOKEN: QBtmoh4L/Ao60rmiLSOV2Sh2z8/LRm2gj6G+bPiKFLZcFW6vLThP3KoLujHwVNH31PTRdn2l2kQZ1m7yiVHG1FPb88oIbqKMvzHtLNOzigPjIFhNehvGJk9NpgLA79oi6Uv0+AWqsa/aOLJpdnLvyCyKABnfPbDriFDu4IrzbkvWJ6rV3rn5rKDtNbi5ViPU75LwtjrTqyLZjzzBg46I22UXO5idNSn/R7D89IkLzgvmsx0CAYddn1yVDsrEkbwwQy0S3PE4XPgdxQGdlRYfBTWjFN90QHUgnf7bw6SP3XGqd5rF/0qPZZbvNaEuAM2ukrxjPJGjujn8lrCuvbVnpvhxdfmfOzqnWxB1ERPLnKrbvY2uH56kH3SJpe/zBuq+B8AmkkVt6eCe3xxULgWCGN7PFBSYkIC+g1fBHKDxtyCgEAYjw0Ghg/3ZkcYtYNKD53YSwkJ3KEXlUhZgSjYZh7nOuAUri+silEhRDBXb4Bsli17cQABSBz7WLPH04dJbtdCvf/yVkDb82b0tmIoZrZX4J1KJwIGwh8TeRRT8z+GVxKNhlShm2R5BVyzgP9qwNZIyy9sAQR2LcxiXu6tFYjuboIe7hwe2+Bxry2SaCbJ1RZrU9eT/TAgbIV0/eBYflJH/3kmoI7Ko8kDO5O1w6CWrI7J928EnC8s9ht4sjdg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
