appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: W00Z5ZcWvbV6dNgn3ZTRr2F7KGPfIBhUAcVYw7vdJ5xeyfflzyI6kmbzS3m2TkWXGUfFx1Bz7SUkd/teCrpBwLf/VG1S8DBKtSs77EXiEFmgQkQVM9Uujb+eCwiwzG3i9VEbeFNBPuHFdXnVvPYCuI4QLGU+w1Wf36dzt2vKTI+esIxXMIQlri9LVZ4hpyHHIAAo0Knha1CFrAJzw85Wi3Nl2gmQYF6R/VUhEpi59WJhWVMO1JrEePdBkAvIKt4KzOa1LR3kGFY+6h/XUkRt4zJcmKAn8YjPqG5kNsCA8k1Ee8pPhVwU465N4eaNuSl9ybK7tqcsbA0vUefiHVgahJ5PwlMbeGuxuLG7P/2U75/bllafiTIxzJJwH9fmgKS2YNlcjTGfBhT00GLcF1V6JW2LzB0vDnQo411e5FzCkVb1n5CMn4IVmWjQCSRzFIeM8vbKZwvrkv7CzKSpi4LDiphdJkokhQq96bmjjYGrAW8fzF5/z11UDX/xjpFmTzMzjFUAfZuy5aCFomttbX5iH1LnhTMAzEyvR3AtqX4NzCICIoYHC7TsbsWJO65T6ehXGzI9ugkkfO99fUzVVg7jjntfm9FkK/3IRESSO5jtvWjg13llneb8xYc7GQQCxx9UWBoFe1Z1XwusDw3snjAoj9usV/mmZjc/CioL2LE5Lg8=}
